"resource/vgui base/SoundscapeSelectorPanel.res"
{
    "SoundscapeSelectorPanel"
    {
        "fieldName"          "SoundscapeSelectorPanel"
        "xpos"               "c-215"
        "ypos"               "c-250"
        "wide"               "430"
        "tall"               "500"
        "visible"            "1"
        "enabled"            "1"
        "settitlebarvisible" "1"
        "title"              "Soundscape Resource Browser"
    }

	"SoundList"
	{
		"ControlName" 		"ListPanel"
		"fieldName"		"SoundList"
		"xpos" 		"12"
		"ypos"		"32"
		"wide"		"407"
		"tall"		"309"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"SoundNameLabel"
	{
		"ControlName" 		"Label"
		"fieldName"		"SoundNameLabel"
		"xpos" 		"10"
		"ypos"		"350"
		"wide"		"90"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Name:"
		"textAlignment"		"east"
	}
	"SoundNameTextEntry"
	{
		"ControlName" 		"TextEntry"
		"fieldName"		"SoundNameTextEntry"
		"xpos" 		"110"
		"ypos"		"350"
		"wide"		"310"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"maxchars"		"512"
		"unicode"		"0"
	}
	"SoundFilterLabel"
	{
		"ControlName" 		"Label"
		"fieldName"		"SoundFilterLabel"
		"xpos" 		"10"
		"ypos"		"380"
		"wide"		"90"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Filter:"
		"textAlignment"		"east"
	}
	"SoundFilterTextEntry"
	{
		"ControlName" 		"TextEntry"
		"fieldName"		"SoundFilterTextEntry"
		"xpos" 		"110"
		"ypos"		"380"
		"wide"		"310"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"maxchars"		"256"
		"unicode"		"0"
	}
	
	"AutoplaySoundsCheckButton"
	{
		"ControlName" 		"CheckButton"
		"fieldName"		"AutoplaySoundsCheckButton"
		"xpos" 		"20"
		"ypos"		"410"
		"wide"		"150"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Autoplay Soundscapes"
	}
	"SoundVolumeLabel"
	{
		"ControlName" 		"Label"
		"fieldName"		"SoundVolumeLabel"
		"xpos" 		"170"
		"ypos"		"410"
		"wide"		"115"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"Volume:"
		"textAlignment"		"east"
	}
	"SoundVolumeSlider"
	{
		"ControlName" 		"Slider"
		"fieldName"		"SoundVolumeSlider"
		"xpos" 		"290"
		"ypos"		"410"
		"wide"		"135"
		"tall"		"20"
		"rangeMin"		"0"
		"rangeMax"		"100"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"ApplyButton"
	{
		"ControlName" 		"Button"
		"fieldName"		"ApplyButton"
		"xpos" 		"15"
		"ypos"		"440"
		"wide"		"125"
		"tall"		"20"
		"command"		"Apply"
		"labelText"		"Apply"
		"textAlignment" "center"
		"visible"		"1"
		"enabled"		"1"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
	}
	"PreviewButton"
	{
		"ControlName" 		"Button"
		"fieldName"		"PreviewButton"
		"xpos" 		"145"
		"ypos"		"440"
		"wide"		"125"
		"tall"		"20"
		"command"		"Preview"
		"labelText"		"Preview"
		"textAlignment" "center"
		"visible"		"1"
		"enabled"		"1"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
	}
	"CancelButton"
	{
		"ControlName" 		"Button"
		"fieldName"		"CancelButton"
		"xpos" 		"15"
		"ypos"		"465"
		"wide"		"125"
		"tall"		"20"
		"command"		"Close"
		"labelText"		"Cancel"
		"textAlignment" "center"
		"visible"		"1"
		"enabled"		"1"
		"default"		"1"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
	}
	"StopButton"
	{
		"ControlName" 		"Button"
		"fieldName"		"StopButton"
		"xpos" 		"145"
		"ypos"		"465"
		"wide"		"125"
		"tall"		"20"
		"command"		"Stop"
		"labelText"		"Stop"
		"textAlignment" "center"
		"visible"		"1"
		"enabled"		"1"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
	}
}