"resource/vgui base/SoundscapeEditorPanel.res"
{
    "SoundscapeEditorPanel"
    {
        "ControlName"        "CSoundscapeEditorPanel"
        "fieldName"          "SoundscapeEditorPanel"
        "xpos"               "c-400"
        "ypos"               "c-349"
        "wide"               "800"
        "tall"               "665"
        "visible"            "1"
        "enabled"            "1"
        "settitlebarvisible" "1"
        "title"              "Soundscape Editor"
    }
	
	"FileButton"
	{
		"ControlName" 		"Button"
		"fieldName"			"FileButton"
        "xpos"          	"18"
        "ypos"          	"30"
        "wide"          	"50"
        "tall"          	"18"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"File"
		"command"			"OpenFileMenu"
		"textAlignment"		"center"
		"sound_released"	"ui/buttonclickrelease.wav"
		"sound_armed"	 	"ui/buttonrollover.wav"
	}
	"OpenButton"
	{
		"ControlName" 		"Button"
		"fieldName"			"OpenButton"
        "xpos"          	"68"
        "ypos"          	"30"
        "wide"          	"50"
        "tall"          	"18"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Open"
		"command"			"OpenOpenMenu"
		"textAlignment"		"center"
		"sound_released"	"ui/buttonclickrelease.wav"
		"sound_armed"	 	"ui/buttonrollover.wav"
	}
	"TopMenuDivider"
	{
		"ControlName" 		"Divider"
		"fieldName"			"TopMenuDivider"
        "xpos"          	"15"
        "ypos"          	"47"
		"zpos"				"-1"
        "wide"          	"770"
        "tall"          	"2"
		"visible"			"1"
		"enabled"			"1"
	}
	
	"SoundscapeListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "SoundscapeListPanel"
        "xpos"               "15"
        "ypos"               "55"
        "wide"               "300"
        "tall"               "580"
        "visible"            "1"
        "enabled"            "1"
    }
    "EventListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "EventListPanel"
        "xpos"               "325"
        "ypos"               "325"
        "wide"               "225"
        "tall"               "310"
        "visible"            "1"
        "enabled"            "0"
    }
    "RandomWaveListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "RandomWaveListPanel"
        "xpos"               "560"
        "ypos"               "325"
        "wide"               "225"
        "tall"               "310"
        "visible"            "1"
        "enabled"            "0"
    }
	"DataListPanel"
    {
        "ControlName"        "CSoundscapeEditorDataPanel"
        "fieldName"          "DataListPanel"
        "xpos"               "325"
        "ypos"               "55"
        "wide"               "460"
        "tall"               "205"
        "visible"            "1"
        "enabled"            "1"
    }
	
	"SoundTextEntry"
    {
        "ControlName"        "TextEntry"
        "fieldName"          "SoundTextEntry"
        "xpos"               "325"
        "ypos"               "265"
        "wide"               "330"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "0"
		"maxchars"			 "512"
    }
	"SoundButton"
    {
        "ControlName"        "Button"
        "fieldName"          "SoundButton"
        "xpos"               "660"
        "ypos"               "265"
        "wide"               "125"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "1"
        "visible"            "1"
		"labelText"          "Change Sound"
		"command"			 "OpenSoundList"
		"textAlignment"      "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	"SoundscapeButton"
    {
        "ControlName"        "Button"
        "fieldName"          "SoundscapeButton"
        "xpos"               "660"
        "ypos"               "265"
        "wide"               "125"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "0"
        "visible"            "0"
		"labelText"          "Change Soundscape"
		"command"			 "OpenSoundscapeList"
		"textAlignment"      "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	
	"PlaySoundscapeCheckButton"
	{
		"ControlName" 	"CheckButton"
		"fieldName"		"PlaySoundscapeCheckButton"
        "xpos"          "325"
        "ypos"          "295"
        "wide"          "225"
        "tall"          "25"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"Play Soundscape"
		"command"		"RestartSoundscape"
	}
	"RestartSoundscapeButton"
	{
		"ControlName" 		"Button"
		"fieldName"			"RestartSoundscapeButton"
        "xpos"          	"560"
        "ypos"          	"298"
        "wide"          	"225"
        "tall"          	"20"
		"visible"			"1"
		"enabled"			"0"
		"labelText"			"Restart Soundscape"
		"command"			"RestartSoundscape"
		"textAlignment"		"center"
		"sound_released"	"ui/buttonclickrelease.wav"
		"sound_armed"	 	"ui/buttonrollover.wav"
	}
	
	//credits
	"CreditsURLLabel"
	{
		"ControlName"        "URLLabel"
		"fieldName"          "CreditsURLLabel"
		"xpos"               "15"
		"ypos"               "637"
		"wide"               "400"
		"tall"               "20"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Created by WadDelz (https://www.youtube.com/@WadDeIz_Real)"
		"URLText"			 "https://www.youtube.com/@WadDeIz_Real"
		"default"            "1"
	}
	
	//how to use
	"TutorialURLLabel"
	{
		"ControlName"        "URLLabel"
		"fieldName"          "TutorialURLLabel"
		"xpos"               "500"
		"ypos"               "637"
		"wide"               "285"
		"tall"               "20"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Tutorial on how to use"
		"URLText"			 "https://developer.valvesoftware.com/wiki/How_to_use_vgui_soundscape_maker"
		"textAlignment"		 "east"
	}
}