"resource/vgui base/SoundscapeEditorPanel.res"
{
    "SoundscapeEditorPanel"
    {
        "ControlName"        "CSoundscapeEditorPanel"
        "fieldName"          "SoundscapeEditorPanel"
        "xpos"               "c-400"
        "ypos"               "c-349"
        "wide"               "800"
        "tall"               "698"
        "visible"            "1"
        "enabled"            "1"
        "settitlebarvisible" "1"
        "title"              "Soundscape Editor"
    }
	
	"SoundscapeListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "SoundscapeListPanel"
        "xpos"               "15"
        "ypos"               "35"
        "wide"               "300"
        "tall"               "580"
        "visible"            "1"
        "enabled"            "1"
    }
	
    "EventListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "EventListPanel"
        "xpos"               "325"
        "ypos"               "305"
        "wide"               "225"
        "tall"               "310"
        "visible"            "1"
        "enabled"            "0"
    }
    "RandomWaveListPanel"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "RandomWaveListPanel"
        "xpos"               "560"
        "ypos"               "305"
        "wide"               "225"
        "tall"               "310"
        "visible"            "1"
        "enabled"            "0"
    }
	
	"PlaySoundscapeCheckButton"
	{
		"ControlName" 	"CheckButton"
		"fieldName"		"PlaySoundscapeCheckButton"
        "xpos"          "325"
        "ypos"          "275"
        "wide"          "225"
        "tall"          "25"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"Play Soundscape"
		"command"		"RestartSoundscape"
	}
	"RestartSoundscapeButton"
	{
		"ControlName" 		"Button"
		"fieldName"			"RestartSoundscapeButton"
        "xpos"          	"560"
        "ypos"          	"278"
        "wide"          	"225"
        "tall"          	"20"
		"visible"			"1"
		"enabled"			"0"
		"labelText"			"Restart Soundscape"
		"command"			"RestartSoundscape"
		"textAlignment"		"center"
		"sound_released"	"ui/buttonclickrelease.wav"
		"sound_armed"	 	"ui/buttonrollover.wav"
	}
	
	"DataListPanel"
    {
        "ControlName"        "CSoundscapeEditorDataPanel"
        "fieldName"          "DataListPanel"
        "xpos"               "325"
        "ypos"               "35"
        "wide"               "460"
        "tall"               "205"
        "visible"            "1"
        "enabled"            "1"
    }
	
	"SoundTextEntry"
    {
        "ControlName"        "TextEntry"
        "fieldName"          "SoundTextEntry"
        "xpos"               "325"
        "ypos"               "245"
        "wide"               "330"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "0"
		"maxchars"			 "512"
    }
	"SoundButton"
    {
        "ControlName"        "Button"
        "fieldName"          "SoundButton"
        "xpos"               "660"
        "ypos"               "245"
        "wide"               "125"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "1"
        "visible"            "1"
		"labelText"          "Change Sound"
		"command"			 "OpenSoundList"
		"textAlignment"      "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	"SoundscapeButton"
    {
        "ControlName"        "Button"
        "fieldName"          "SoundscapeButton"
        "xpos"               "660"
        "ypos"               "245"
        "wide"               "125"
        "tall"               "25"
        "visible"            "1"
        "enabled"            "0"
        "visible"            "0"
		"labelText"          "Change Soundscape"
		"command"			 "OpenSoundscapeList"
		"textAlignment"      "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	
	"NewSoundscapeButton"
	{
		"ControlName"        "Button"
		"fieldName"          "NewSoundscapeButton"
		"xpos"               "15"
		"ypos"               "620"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "New Soundscape File"
		"command"            "NewSoundscapeFile"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"SaveSoundscapeButton"
	{
		"ControlName"        "Button"
		"fieldName"          "SaveSoundscapeButton"
		"xpos"               "209"
		"ypos"               "620"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Save Soundscape File"
		"command"            "SaveSoundscape"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"LoadSoundscapeButton"
	{
		"ControlName"        "Button"
		"fieldName"          "LoadSoundscapeButton"
		"xpos"               "403"
		"ypos"               "620"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Load Soundscape File"
		"command"            "LoadSoundscape"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"OpenTextEditorButton"
	{
		"ControlName"        "Button"
		"fieldName"          "OpenTextEditorButton"
		"xpos"               "597"
		"ypos"               "620"
		"wide"               "188"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Open Text Editor"
		"command"            "OpenTextEditor"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"OpenPositionPanelButton"
	{
		"ControlName"        "Button"
		"fieldName"          "OpenPositionPanelButton"
		"xpos"               "15"
		"ypos"               "646"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Open Position Editor"
		"command"            "OpenPositionEditor"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"OpenDebugPanelButton"
	{
		"ControlName"        "Button"
		"fieldName"          "OpenDebugPanelButton"
		"xpos"               "209"
		"ypos"               "646"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Open Debugger"
		"command"            "OpenDebugPanel"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"OpenPreloadedSoundscapesPanelButton"
	{
		"ControlName"        "Button"
		"fieldName"          "OpenPreloadedSoundscapesPanel"
		"xpos"               "403"
		"ypos"               "646"
		"wide"               "189"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Edit Preloaded Soundscapes"
		"command"            "OpenPreloadedSoundscapesPanel"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	"OpenManifestEditorPanelButton"
	{
		"ControlName"        "Button"
		"fieldName"          "OpenManifestEditorPanelButton"
		"xpos"               "597"
		"ypos"               "646"
		"wide"               "188"
		"tall"               "22"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Open Manifest Editor"
		"command"            "OpenManifestEditorPanel"
		"sound_released"     "ui/buttonclickrelease.wav"
		"sound_armed"        "ui/buttonrollover.wav"
		"textAlignment"      "center"
	}
	
	//credits
	"CreditsURLLabel"
	{
		"ControlName"        "URLLabel"
		"fieldName"          "CreditsURLLabel"
		"xpos"               "15"
		"ypos"               "672"
		"wide"               "400"
		"tall"               "20"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Created by WadDelz (https://www.youtube.com/@WadDeIz_Real)"
		"URLText"			 "https://www.youtube.com/@WadDeIz_Real"
		"default"            "1"
	}
	
	//credits
	"TutorialURLLabel"
	{
		"ControlName"        "URLLabel"
		"fieldName"          "TutorialURLLabel"
		"xpos"               "500"
		"ypos"               "672"
		"wide"               "285"
		"tall"               "20"
		"visible"            "1"
		"enabled"            "1"
		"labelText"          "Tutorial on how to use"
		"URLText"			 "https://developer.valvesoftware.com/wiki/How_to_use_vgui_soundscape_maker"
		"textAlignment"		 "east"
	}
}