"resource/vgui base/SoundscapeEditorPanelPreloadedSoundscapesDialog.res"
{
    "SoundscapeMakerPreloadedSoundscapesPanel"
    {
        "ControlName"        "CSoundscapeMakerPreloadedSoundscapesPanel"
        "fieldName"          "SoundscapeMakerPreloadedSoundscapesPanel"
        "xpos"               "c-225"
        "ypos"               "c-200"
        "wide"               "450"
        "tall"               "400"
        "visible"            "1"
        "enabled"            "1"
        "settitlebarvisible" "1"
		"title" 			 "Preloaded Soundscapes"
    }
	
	"PreloadList"
    {
        "ControlName"        "ListPanel"
        "fieldName"          "PreloadList"
        "xpos"               "5"
        "ypos"               "30"
        "wide"               "440"
        "tall"               "285"
        "visible"            "1"
        "enabled"            "1"
    }
	
	"NewItemButton"
    {
        "ControlName"        "Button"
        "fieldName"          "NewItemButton"
        "xpos"               "5"
        "ypos"               "320"
        "wide"               "218"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "1"
		"labelText"		     "Add New File"
		"command"		     "NewFile"
		"textAlignment"	     "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
		"default"			 "1"
    }
	"RemoveItemButton"
    {
        "ControlName"        "Button"
        "fieldName"          "RemoveItemButton"
        "xpos"               "228"
        "ypos"               "320"
        "wide"               "218"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "0"
		"labelText"		     "Remove Selected File"
		"command"		     "RemoveFile"
		"textAlignment"	     "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	"MoveItemUpButton"
    {
        "ControlName"        "Button"
        "fieldName"          "MoveItemUpButton"
        "xpos"               "5"
        "ypos"               "345"
        "wide"               "218"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "0"
		"labelText"		     "Move Selected Item Up"
		"command"		     "MoveItemUp"
		"textAlignment"	     "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	"MoveItepDownButton"
    {
        "ControlName"        "Button"
        "fieldName"          "MoveItepDownButton"
        "xpos"               "228"
        "ypos"               "345"
        "wide"               "218"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "0"
		"labelText"		     "Move Selected Item Down"
		"command"		     "MoveItemDown"
		"textAlignment"	     "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
	"ClearItemsButton"
    {
        "ControlName"        "Button"
        "fieldName"          "ClearItemsButton"
        "xpos"               "5"
        "ypos"               "370"
        "wide"               "440"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "0"
		"labelText"		     "Clear All Files"
		"command"		     "ClearFiles"
		"textAlignment"	     "center"
		"sound_released"	 "ui/buttonclickrelease.wav"
		"sound_armed"	 	 "ui/buttonrollover.wav"
    }
}