-- Soundscapes are read from the entities themselves (no reliance on captured keyvalues)
SetCV( "amod_soundscapes_disable", 0 )
GM_LOAD( "modules/sv_soundscapes.lua" )
MakeEnt( "env_soundscape", { name = "a", pos = Vector( 0, 0, 0 ), iv = { m_soundscapeName = "inside.canals_start", m_flRadius = 256, m_bDisabled = false } } )
MakeEnt( "env_soundscape", { name = "b", pos = Vector( 5000, 0, 0 ), iv = { m_soundscapeName = "d1_canals.outside", m_flRadius = -1, m_bDisabled = true } } )
MakeEnt( "env_soundscape_proxy", { pos = Vector( 9000, 0, 0 ), iv = { m_MainSoundscapeName = "a", m_flRadius = 128 } } )
local P = MakePlayer( "p", Vector( 10, 0, 0 ) )
hook.Run( "InitPostEntity" )
assert( HL2A.SoundscapeCount() == 3 )
Tick( 1 )
assert( P:GetNW2String( "hl2a.soundscape" ) == "inside.canals_start", "nearest audible, enabled soundscape" )
